---

name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: ci

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 16.x, 14.x, 12.x]
        database-type: [postgres, mysql, mssql, sqlite3]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Start Database(s)
        run: |
          docker-compose \
            --file "scripts/docker-compose.yml" \
            up \
              --detach \
              --build \
              "${{ matrix.database-type }}"
        if: matrix.database-type != 'sqlite3'

      - name: Initialize Database(s)
        run: |
          docker-compose \
            --file "scripts/docker-compose.yml" \
            up \
              --detach \
              "wait${{ matrix.database-type }}"
        if: matrix.database-type != 'sqlite3'

      - name: Run npm install
        run: npm install

      - name: Run Tests
        run: npm run test
        env:
          DB: ${{ matrix.database-type }}

      - name: Stop Database(s)
        run: |
          docker-compose \
            --file "scripts/docker-compose.yml" \
            down
        if: matrix.database-type != 'sqlite3'
