name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print OPEN_AI_API_KEY secret
        run: echo ${{ secrets.OPEN_AI_API_KEY }}
      - name: Install dependencies & build Nest app
        run: |
          npm install
          npm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jadenxiong/chat-query-backend:latest
          attests: |
             OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}
             MODEL_NAME=${{ secrets.MODEL_NAME }}
             BASE_URL=${{ secrets.BASE_URL }}
             DB_HOST=${{ secrets.DB_HOST }}
             DB_PORT=${{ secrets.DB_PORT }}
